apiVersion: v1
kind: Service
metadata:
  name: meed-mitigation-prioritizer-frontend-service-prod
  namespace: default
  labels:
    app: meed-mitigation-prioritizer-frontend-prod
spec:
  selector:
    app: meed-mitigation-prioritizer-frontend-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
  type: ClusterIP
