apiVersion: v1
kind: Service
metadata:
  name: meed-mitigation-prioritizer-frontend-service-dev
  namespace: default
  labels:
    app: meed-mitigation-prioritizer-frontend-dev
spec:
  selector:
    app: meed-mitigation-prioritizer-frontend-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
  type: ClusterIP
