// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hiap/CityProfile.tsx": () => import("../components/mockups/hiap/CityProfile.tsx"),
  "./components/mockups/hiap/EmissionsAdjust.tsx": () => import("../components/mockups/hiap/EmissionsAdjust.tsx"),
  "./components/mockups/hiap/EmissionsReview.tsx": () => import("../components/mockups/hiap/EmissionsReview.tsx"),
  "./components/mockups/hiap/Landing.tsx": () => import("../components/mockups/hiap/Landing.tsx"),
  "./components/mockups/hiap/PolicyAlignment.tsx": () => import("../components/mockups/hiap/PolicyAlignment.tsx"),
  "./components/mockups/hiap/PreflightSummary.tsx": () => import("../components/mockups/hiap/PreflightSummary.tsx"),
  "./components/mockups/hiap/Processing.tsx": () => import("../components/mockups/hiap/Processing.tsx"),
  "./components/mockups/hiap/Regulations.tsx": () => import("../components/mockups/hiap/Regulations.tsx"),
  "./components/mockups/hiap/Results.tsx": () => import("../components/mockups/hiap/Results.tsx"),
  "./components/mockups/hiap/ResultsPanel.tsx": () => import("../components/mockups/hiap/ResultsPanel.tsx"),
  "./components/mockups/hiap/Socioeconomic.tsx": () => import("../components/mockups/hiap/Socioeconomic.tsx"),
  "./components/mockups/hiap/StrategicPreferences.tsx": () => import("../components/mockups/hiap/StrategicPreferences.tsx")
};
